/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OnboardingMotivationRouteImport } from './routes/onboarding/motivation'
import { Route as AppToolsRouteImport } from './routes/_app/tools'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReviewRouteImport } from './routes/_app/review'
import { Route as AppHelpRouteImport } from './routes/_app/help'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppChallengeRouteImport } from './routes/_app/challenge'
import { Route as AppAchievementsRouteImport } from './routes/_app/achievements'
import { Route as AppModulesModuleIdIndexRouteImport } from './routes/_app/modules/$moduleId/index'
import { Route as AppModulesModuleIdResultsRouteImport } from './routes/_app/modules/$moduleId/results'
import { Route as AppModulesModuleIdLessonRouteImport } from './routes/_app/modules/$moduleId/lesson'
import { Route as AppModulesModuleIdExerciseRouteImport } from './routes/_app/modules/$moduleId/exercise'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingMotivationRoute = OnboardingMotivationRouteImport.update({
  id: '/onboarding/motivation',
  path: '/onboarding/motivation',
  getParentRoute: () => rootRouteImport,
} as any)
const AppToolsRoute = AppToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChallengeRoute = AppChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppModulesModuleIdIndexRoute = AppModulesModuleIdIndexRouteImport.update({
  id: '/modules/$moduleId/',
  path: '/modules/$moduleId/',
  getParentRoute: () => AppRoute,
} as any)
const AppModulesModuleIdResultsRoute =
  AppModulesModuleIdResultsRouteImport.update({
    id: '/modules/$moduleId/results',
    path: '/modules/$moduleId/results',
    getParentRoute: () => AppRoute,
  } as any)
const AppModulesModuleIdLessonRoute =
  AppModulesModuleIdLessonRouteImport.update({
    id: '/modules/$moduleId/lesson',
    path: '/modules/$moduleId/lesson',
    getParentRoute: () => AppRoute,
  } as any)
const AppModulesModuleIdExerciseRoute =
  AppModulesModuleIdExerciseRouteImport.update({
    id: '/modules/$moduleId/exercise',
    path: '/modules/$moduleId/exercise',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AppAchievementsRoute
  '/challenge': typeof AppChallengeRoute
  '/dashboard': typeof AppDashboardRoute
  '/help': typeof AppHelpRoute
  '/review': typeof AppReviewRoute
  '/settings': typeof AppSettingsRoute
  '/tools': typeof AppToolsRoute
  '/onboarding/motivation': typeof OnboardingMotivationRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/modules/$moduleId/exercise': typeof AppModulesModuleIdExerciseRoute
  '/modules/$moduleId/lesson': typeof AppModulesModuleIdLessonRoute
  '/modules/$moduleId/results': typeof AppModulesModuleIdResultsRoute
  '/modules/$moduleId/': typeof AppModulesModuleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AppAchievementsRoute
  '/challenge': typeof AppChallengeRoute
  '/dashboard': typeof AppDashboardRoute
  '/help': typeof AppHelpRoute
  '/review': typeof AppReviewRoute
  '/settings': typeof AppSettingsRoute
  '/tools': typeof AppToolsRoute
  '/onboarding/motivation': typeof OnboardingMotivationRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/modules/$moduleId/exercise': typeof AppModulesModuleIdExerciseRoute
  '/modules/$moduleId/lesson': typeof AppModulesModuleIdLessonRoute
  '/modules/$moduleId/results': typeof AppModulesModuleIdResultsRoute
  '/modules/$moduleId': typeof AppModulesModuleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/achievements': typeof AppAchievementsRoute
  '/_app/challenge': typeof AppChallengeRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/review': typeof AppReviewRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tools': typeof AppToolsRoute
  '/onboarding/motivation': typeof OnboardingMotivationRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_app/modules/$moduleId/exercise': typeof AppModulesModuleIdExerciseRoute
  '/_app/modules/$moduleId/lesson': typeof AppModulesModuleIdLessonRoute
  '/_app/modules/$moduleId/results': typeof AppModulesModuleIdResultsRoute
  '/_app/modules/$moduleId/': typeof AppModulesModuleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/challenge'
    | '/dashboard'
    | '/help'
    | '/review'
    | '/settings'
    | '/tools'
    | '/onboarding/motivation'
    | '/onboarding/'
    | '/modules/$moduleId/exercise'
    | '/modules/$moduleId/lesson'
    | '/modules/$moduleId/results'
    | '/modules/$moduleId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/challenge'
    | '/dashboard'
    | '/help'
    | '/review'
    | '/settings'
    | '/tools'
    | '/onboarding/motivation'
    | '/onboarding'
    | '/modules/$moduleId/exercise'
    | '/modules/$moduleId/lesson'
    | '/modules/$moduleId/results'
    | '/modules/$moduleId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/achievements'
    | '/_app/challenge'
    | '/_app/dashboard'
    | '/_app/help'
    | '/_app/review'
    | '/_app/settings'
    | '/_app/tools'
    | '/onboarding/motivation'
    | '/onboarding/'
    | '/_app/modules/$moduleId/exercise'
    | '/_app/modules/$moduleId/lesson'
    | '/_app/modules/$moduleId/results'
    | '/_app/modules/$moduleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingMotivationRoute: typeof OnboardingMotivationRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/motivation': {
      id: '/onboarding/motivation'
      path: '/onboarding/motivation'
      fullPath: '/onboarding/motivation'
      preLoaderRoute: typeof OnboardingMotivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tools': {
      id: '/_app/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AppToolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/challenge': {
      id: '/_app/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof AppChallengeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/achievements': {
      id: '/_app/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modules/$moduleId/': {
      id: '/_app/modules/$moduleId/'
      path: '/modules/$moduleId'
      fullPath: '/modules/$moduleId/'
      preLoaderRoute: typeof AppModulesModuleIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modules/$moduleId/results': {
      id: '/_app/modules/$moduleId/results'
      path: '/modules/$moduleId/results'
      fullPath: '/modules/$moduleId/results'
      preLoaderRoute: typeof AppModulesModuleIdResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modules/$moduleId/lesson': {
      id: '/_app/modules/$moduleId/lesson'
      path: '/modules/$moduleId/lesson'
      fullPath: '/modules/$moduleId/lesson'
      preLoaderRoute: typeof AppModulesModuleIdLessonRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modules/$moduleId/exercise': {
      id: '/_app/modules/$moduleId/exercise'
      path: '/modules/$moduleId/exercise'
      fullPath: '/modules/$moduleId/exercise'
      preLoaderRoute: typeof AppModulesModuleIdExerciseRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppChallengeRoute: typeof AppChallengeRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHelpRoute: typeof AppHelpRoute
  AppReviewRoute: typeof AppReviewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppToolsRoute: typeof AppToolsRoute
  AppModulesModuleIdExerciseRoute: typeof AppModulesModuleIdExerciseRoute
  AppModulesModuleIdLessonRoute: typeof AppModulesModuleIdLessonRoute
  AppModulesModuleIdResultsRoute: typeof AppModulesModuleIdResultsRoute
  AppModulesModuleIdIndexRoute: typeof AppModulesModuleIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppChallengeRoute: AppChallengeRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHelpRoute: AppHelpRoute,
  AppReviewRoute: AppReviewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppToolsRoute: AppToolsRoute,
  AppModulesModuleIdExerciseRoute: AppModulesModuleIdExerciseRoute,
  AppModulesModuleIdLessonRoute: AppModulesModuleIdLessonRoute,
  AppModulesModuleIdResultsRoute: AppModulesModuleIdResultsRoute,
  AppModulesModuleIdIndexRoute: AppModulesModuleIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingMotivationRoute: OnboardingMotivationRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
